### ISSUE TITLE
[bug]ResManagerImpl中gc死循环了

### ISSUE THREAD

**Issue by xjn9854262** [GregGJ/DrongoCC#1]
偶然间看到搜到这个框架开源，刚好需要，很感谢楼主开源分享。

但是我在使用期间，ResManagerImpl->gc的for循环中是否忘记移除了删除的元素，导致死循环了。

**Comment by GregGJ** [comment]
非常感谢你提的BUG，这个框架是我从业10几年总结的一些东西，希望能够帮到你。
正在慢慢整理，预计在这月中旬能全部整理完。
